version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./scripts/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/app
      # - ./migrations:/src/migrations
      - ./scripts:/src/scripts
      # - ./tests:/src/tests
      # - ./alembic.ini:/src/alembic.ini
